/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../../app/routes/__root';
import { Route as UnprotectedRouteImport } from './../../app/routes/_unprotected';
import { Route as ProtectedRouteImport } from './../../app/routes/_protected';
import { Route as ProtectedIndexRouteImport } from './../../app/routes/_protected/index';
import { Route as UnprotectedVerificationRouteImport } from './../../app/routes/_unprotected/verification';
import { Route as UnprotectedRegisterRouteImport } from './../../app/routes/_unprotected/register';
import { Route as UnprotectedLoginRouteImport } from './../../app/routes/_unprotected/login';
import { Route as ProtectedSettingsRouteImport } from './../../app/routes/_protected/settings';
import { Route as ProtectedServersRouteImport } from './../../app/routes/_protected/servers';
import { Route as ProtectedRequestsRouteImport } from './../../app/routes/_protected/requests';

const UnprotectedRoute = UnprotectedRouteImport.update({
  id: '/_unprotected',
  getParentRoute: () => rootRouteImport,
} as any);
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any);
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any);
const UnprotectedVerificationRoute = UnprotectedVerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => UnprotectedRoute,
} as any);
const UnprotectedRegisterRoute = UnprotectedRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => UnprotectedRoute,
} as any);
const UnprotectedLoginRoute = UnprotectedLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => UnprotectedRoute,
} as any);
const ProtectedSettingsRoute = ProtectedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProtectedRoute,
} as any);
const ProtectedServersRoute = ProtectedServersRouteImport.update({
  id: '/servers',
  path: '/servers',
  getParentRoute: () => ProtectedRoute,
} as any);
const ProtectedRequestsRoute = ProtectedRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => ProtectedRoute,
} as any);

export interface FileRoutesByFullPath {
  '/requests': typeof ProtectedRequestsRoute;
  '/servers': typeof ProtectedServersRoute;
  '/settings': typeof ProtectedSettingsRoute;
  '/login': typeof UnprotectedLoginRoute;
  '/register': typeof UnprotectedRegisterRoute;
  '/verification': typeof UnprotectedVerificationRoute;
  '/': typeof ProtectedIndexRoute;
}
export interface FileRoutesByTo {
  '/requests': typeof ProtectedRequestsRoute;
  '/servers': typeof ProtectedServersRoute;
  '/settings': typeof ProtectedSettingsRoute;
  '/login': typeof UnprotectedLoginRoute;
  '/register': typeof UnprotectedRegisterRoute;
  '/verification': typeof UnprotectedVerificationRoute;
  '/': typeof ProtectedIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/_protected': typeof ProtectedRouteWithChildren;
  '/_unprotected': typeof UnprotectedRouteWithChildren;
  '/_protected/requests': typeof ProtectedRequestsRoute;
  '/_protected/servers': typeof ProtectedServersRoute;
  '/_protected/settings': typeof ProtectedSettingsRoute;
  '/_unprotected/login': typeof UnprotectedLoginRoute;
  '/_unprotected/register': typeof UnprotectedRegisterRoute;
  '/_unprotected/verification': typeof UnprotectedVerificationRoute;
  '/_protected/': typeof ProtectedIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/requests'
    | '/servers'
    | '/settings'
    | '/login'
    | '/register'
    | '/verification'
    | '/';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/requests'
    | '/servers'
    | '/settings'
    | '/login'
    | '/register'
    | '/verification'
    | '/';
  id:
    | '__root__'
    | '/_protected'
    | '/_unprotected'
    | '/_protected/requests'
    | '/_protected/servers'
    | '/_protected/settings'
    | '/_unprotected/login'
    | '/_unprotected/register'
    | '/_unprotected/verification'
    | '/_protected/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren;
  UnprotectedRoute: typeof UnprotectedRouteWithChildren;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_unprotected': {
      id: '/_unprotected';
      path: '';
      fullPath: '';
      preLoaderRoute: typeof UnprotectedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_protected': {
      id: '/_protected';
      path: '';
      fullPath: '';
      preLoaderRoute: typeof ProtectedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_protected/': {
      id: '/_protected/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof ProtectedIndexRouteImport;
      parentRoute: typeof ProtectedRoute;
    };
    '/_unprotected/verification': {
      id: '/_unprotected/verification';
      path: '/verification';
      fullPath: '/verification';
      preLoaderRoute: typeof UnprotectedVerificationRouteImport;
      parentRoute: typeof UnprotectedRoute;
    };
    '/_unprotected/register': {
      id: '/_unprotected/register';
      path: '/register';
      fullPath: '/register';
      preLoaderRoute: typeof UnprotectedRegisterRouteImport;
      parentRoute: typeof UnprotectedRoute;
    };
    '/_unprotected/login': {
      id: '/_unprotected/login';
      path: '/login';
      fullPath: '/login';
      preLoaderRoute: typeof UnprotectedLoginRouteImport;
      parentRoute: typeof UnprotectedRoute;
    };
    '/_protected/settings': {
      id: '/_protected/settings';
      path: '/settings';
      fullPath: '/settings';
      preLoaderRoute: typeof ProtectedSettingsRouteImport;
      parentRoute: typeof ProtectedRoute;
    };
    '/_protected/servers': {
      id: '/_protected/servers';
      path: '/servers';
      fullPath: '/servers';
      preLoaderRoute: typeof ProtectedServersRouteImport;
      parentRoute: typeof ProtectedRoute;
    };
    '/_protected/requests': {
      id: '/_protected/requests';
      path: '/requests';
      fullPath: '/requests';
      preLoaderRoute: typeof ProtectedRequestsRouteImport;
      parentRoute: typeof ProtectedRoute;
    };
  }
}

interface ProtectedRouteChildren {
  ProtectedRequestsRoute: typeof ProtectedRequestsRoute;
  ProtectedServersRoute: typeof ProtectedServersRoute;
  ProtectedSettingsRoute: typeof ProtectedSettingsRoute;
  ProtectedIndexRoute: typeof ProtectedIndexRoute;
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedRequestsRoute: ProtectedRequestsRoute,
  ProtectedServersRoute: ProtectedServersRoute,
  ProtectedSettingsRoute: ProtectedSettingsRoute,
  ProtectedIndexRoute: ProtectedIndexRoute,
};

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren
);

interface UnprotectedRouteChildren {
  UnprotectedLoginRoute: typeof UnprotectedLoginRoute;
  UnprotectedRegisterRoute: typeof UnprotectedRegisterRoute;
  UnprotectedVerificationRoute: typeof UnprotectedVerificationRoute;
}

const UnprotectedRouteChildren: UnprotectedRouteChildren = {
  UnprotectedLoginRoute: UnprotectedLoginRoute,
  UnprotectedRegisterRoute: UnprotectedRegisterRoute,
  UnprotectedVerificationRoute: UnprotectedVerificationRoute,
};

const UnprotectedRouteWithChildren = UnprotectedRoute._addFileChildren(
  UnprotectedRouteChildren
);

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  UnprotectedRoute: UnprotectedRouteWithChildren,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
