/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/auth': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Вход в систему по логину/паролю */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': {
            /** @example chetkii_poc */
            username?: string;
            /** @example 12345678 */
            password?: string;
          };
        };
      };
      responses: {
        /** @description Успешная авторизация */
        200: {
          headers: {
            'Set-Cookie'?: string;
            [name: string]: unknown;
          };
          content: {
            /** @example 3c3beb77-b54a-4733-8c5d-acd7b2680241 */
            text: unknown;
          };
        };
        /** @description Неверный логин/пароль */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/register': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Изменение данных пользователя */
    put: {
      parameters: {
        query?: {
          /** @description Аватар пользователя */
          avatar?: string;
        };
        header?: never;
        path?: never;
        cookie: {
          /** @description Токен авторизации */
          zavodchat_token: parameters['zavodchat_token'];
        };
      };
      requestBody?: {
        content: {
          'application/json': {
            /** @example realnii_poc */
            username?: string;
            /** @example рЯльНыЙ____ПОЦЦЦЦЦ */
            displayname?: string;
            /** @example letmein123 */
            password?: string;
          };
        };
      };
      responses: {
        /** @description Успешное изменение данных */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    /** Регистрация в системе */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: {
        content: {
          'application/json': {
            /** @example chetkii_poc */
            username?: string;
            /** @example Чёткий П0цык */
            displayname?: string;
            /** @example 12345678 */
            password?: string;
          };
        };
      };
      responses: {
        /** @description Успешная регистрация */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Слишком короткий username/password */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Логин занят */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/users/$user_id': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Информация о пользователе */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Информация о пользователе */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['User'];
          };
        };
        /** @description Не существует пользователя с таким user_id */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/user_status': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Изменить свой статус */
    put: {
      parameters: {
        query: {
          /** @description Статус */
          status: components['schemas']['UserStatus'];
        };
        header?: never;
        path?: never;
        cookie: {
          /** @description Токен авторизации */
          zavodchat_token: parameters['zavodchat_token'];
        };
      };
      requestBody?: never;
      responses: {
        /** @description Не существует пользователя с таким user_id */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/servers': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Список серверов, в которых состоит пользователь */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie: {
          /** @description Токен авторизации */
          zavodchat_token: parameters['zavodchat_token'];
        };
      };
      requestBody?: never;
      responses: {
        /** @description Список серверов */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Server'][];
          };
        };
      };
    };
    put?: never;
    /** Создать сервер */
    post: {
      parameters: {
        query: {
          /** @description Имя сервера */
          name: string;
        };
        header?: never;
        path?: never;
        cookie: {
          /** @description Токен авторизации */
          zavodchat_token: parameters['zavodchat_token'];
        };
      };
      requestBody?: never;
      responses: {
        /** @description server_id созданного сервера */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            /** @example 73 */
            text: unknown;
          };
        };
        /** @description Превышено ограничение на количество серверов, которыми владеет пользователь */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/servers/$server_id': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Получить информацию о сервере */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie: {
          /** @description Токен авторизации */
          zavodchat_token: parameters['zavodchat_token'];
        };
      };
      requestBody?: never;
      responses: {
        /** @description Информация о сервере */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Server'];
          };
        };
      };
    };
    /** Изменить параметры сервера */
    put: {
      parameters: {
        query?: {
          /** @description Имя сервера */
          name?: string;
          /** @description ID нового владельца сервера */
          owner_id?: number;
          /** @description Аватар сервера */
          avatar?: string;
        };
        header?: never;
        path?: never;
        cookie: {
          /** @description Токен авторизации */
          zavodchat_token: parameters['zavodchat_token'];
        };
      };
      requestBody?: never;
      responses: {
        /** @description Сервер успешно изменён */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Пользователь с owner_id уже является владельцем сервера */
        202: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Слишком длинное название сервера */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Пользователь с owner_id не состоит на сервере */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    post?: never;
    /** Удалить сервер */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie: {
          /** @description Токен авторизации */
          zavodchat_token: parameters['zavodchat_token'];
        };
      };
      requestBody?: never;
      responses: {
        /** @description Сервер успешно удалён */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/servers/$server_id/users': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Пагинированный список пользователей */
    get: {
      parameters: {
        query: {
          /** @description Начало диапазона (0 - последний пользователь, 1 - предпоследний, и т.д.) */
          start: number;
          /** @description Размер диапазона */
          count: number;
        };
        header?: never;
        path?: never;
        cookie: {
          /** @description Токен авторизации */
          zavodchat_token: parameters['zavodchat_token'];
        };
      };
      requestBody?: never;
      responses: {
        /** @description Список пользователей (может быть < count - означает конец массива пользователей) */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ServerUser'][];
          };
        };
        /** @description Неправильный start (< 0, >= количеству пользователей) / слишком большой count */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/servers/$server_id/users/$user_id': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Информация о пользователе на сервере */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Информация о пользователе */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['ServerUser'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    /** Выгнать пользователя с сервера */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Пользователь был кикнут */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Нет прав на кик / попытка кикнуть пользователя >= ролью / попытка кикнуть владельца */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Пользователь не состоит на сервере */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/servers/$server_id/channels': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Список каналов */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie: {
          /** @description Токен авторизации */
          zavodchat_token: parameters['zavodchat_token'];
        };
      };
      requestBody?: never;
      responses: {
        /** @description Информация обо всех каналах */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Channel'][];
          };
        };
      };
    };
    put?: never;
    /** Создать канал */
    post: {
      parameters: {
        query?: {
          /** @description Имя канала */
          name?: string;
          /** @description 0 - текстовый, 1 - голосовой */
          type?: number;
        };
        header?: never;
        path?: never;
        cookie: {
          /** @description Токен авторизации */
          zavodchat_token: parameters['zavodchat_token'];
        };
      };
      requestBody?: never;
      responses: {
        /** @description channel_id созданного канала */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            /** @example 4 */
            text: unknown;
          };
        };
        /** @description Превышено ограничение на количество каналов на сервере */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/servers/$server_id/channels/$channel_id': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Информация о канале */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie: {
          /** @description Токен авторизации */
          zavodchat_token: parameters['zavodchat_token'];
        };
      };
      requestBody?: never;
      responses: {
        /** @description Информация о канале */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Channel'];
          };
        };
      };
    };
    /** Изменить параметры канала */
    put: {
      parameters: {
        query?: {
          /** @description Имя канала */
          name?: string;
          /** @description 0 - текстовый, 1 - голосовой */
          type?: number;
        };
        header?: never;
        path?: never;
        cookie: {
          /** @description Токен авторизации */
          zavodchat_token: parameters['zavodchat_token'];
        };
      };
      requestBody?: never;
      responses: {
        /** @description Параметры успешно изменены */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    post?: never;
    /** Удалить канал */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie: {
          /** @description Токен авторизации */
          zavodchat_token: parameters['zavodchat_token'];
        };
      };
      requestBody?: never;
      responses: {
        /** @description Канал успешно удалён */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/servers/$server_id/channels/$channel_id/messages': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Пагинированный список сообщений */
    get: {
      parameters: {
        query: {
          /** @description Начало диапазона (0 - последнее сообщение, 1 - предпоследнее, и т.д.) */
          start: number;
          /** @description Размер диапазона */
          count: number;
          /** @description Порядок сообщений (0 - от новых к старым (по умолчанию), 1 - от старых к новым) */
          order?: number;
        };
        header?: never;
        path?: never;
        cookie: {
          /** @description Токен авторизации */
          zavodchat_token: parameters['zavodchat_token'];
        };
      };
      requestBody?: never;
      responses: {
        /** @description Сообщения (может быть < count - означает конец массива сообщений) */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Message'][];
          };
        };
        /** @description Неправильный start (< 0, >= количеству пользователей) / слишком большой count / канал не текстовый */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    /** Отправить сообщение */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie: {
          /** @description Токен авторизации */
          zavodchat_token: parameters['zavodchat_token'];
        };
      };
      requestBody?: {
        content: {
          /** @example папа ты купил молоко? */
          text: unknown;
        };
      };
      responses: {
        /** @description ID созданного сообщения */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            /** @example 377 */
            text: unknown;
          };
        };
        /** @description Пустое сообщение */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/servers/$server_id/channels/$channel_id/messages/$message_id': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Информация о сообщении */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie: {
          /** @description Токен авторизации */
          zavodchat_token: parameters['zavodchat_token'];
        };
      };
      requestBody?: never;
      responses: {
        /** @description Сообщение */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Message'];
          };
        };
      };
    };
    /** Отредактировать сообщение */
    put: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie: {
          /** @description Токен авторизации */
          zavodchat_token: parameters['zavodchat_token'];
        };
      };
      requestBody?: {
        content: {
          /** @example папа ты купил молоко? */
          text: unknown;
        };
      };
      responses: {
        /** @description Сообщение успешно отредактировано */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Пустое сообщение */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Пользователь не является автором сообщения */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    post?: never;
    /** Удалить сообщение */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie: {
          /** @description Токен авторизации */
          zavodchat_token: parameters['zavodchat_token'];
        };
      };
      requestBody?: never;
      responses: {
        /** @description Сообщение успешно удалено */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Пользователь не является автором сообщения и не имеет право на удаление чужих сообщений */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/server_invites/$invite_id': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Вступить на сервер по приглашению */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie: {
          /** @description Токен авторизации */
          zavodchat_token: parameters['zavodchat_token'];
        };
      };
      requestBody?: never;
      responses: {
        /** @description Пользователь был принят на сервер */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Пользователь уже состоит на сервере */
        202: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Приглашение истекло / пользователь забанен */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/servers/$server_id/invites': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Получить список приглашений на сервер */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie: {
          /** @description Токен авторизации */
          zavodchat_token: parameters['zavodchat_token'];
        };
      };
      requestBody?: never;
      responses: {
        /** @description Информация о приглашениях */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Invite'][];
          };
        };
        /** @description У пользователя нет прав на управление приглашениями */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    /** Создать приглашение */
    post: {
      parameters: {
        query?: {
          /** @description Дата и время истечения приглашения (автоматически удаляется из базы данных через некоторый промежуток). Может быть "never" */
          expires?: string;
        };
        header?: never;
        path?: never;
        cookie: {
          /** @description Токен авторизации */
          zavodchat_token: parameters['zavodchat_token'];
        };
      };
      requestBody?: never;
      responses: {
        /** @description ID созданного приглашения */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            /** @example 1e1d184c-679a-494e-ba30-6f1f72bd221e */
            text: unknown;
          };
        };
        /** @description Неправильный формат даты и времени expires */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Превышено ограничение на количество приглашений / у пользователя нет прав на управление приглашениями */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/servers/$server_id/invites/$invite_id': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Информация о приглашении на сервер */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie: {
          /** @description Токен авторизации */
          zavodchat_token: parameters['zavodchat_token'];
        };
      };
      requestBody?: never;
      responses: {
        /** @description Информация о приглашении */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Invite'];
          };
        };
        /** @description У пользователя нет прав на управление приглашениями */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Приглашения с таким ID не существует на сервере */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    /** Изменить параметры приглашения */
    put: {
      parameters: {
        query?: {
          /** @description Дата и время истечения приглашения (автоматически удаляется из базы данных через некоторый промежуток). Может быть "never" */
          expires?: string;
        };
        header?: never;
        path?: never;
        cookie: {
          /** @description Токен авторизации */
          zavodchat_token: parameters['zavodchat_token'];
        };
      };
      requestBody?: never;
      responses: {
        /** @description Приглашение успешно изменено */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Неправильный формат даты и времени expires */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description У пользователя нет прав на управление приглашениями */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Приглашения с таким ID не существует на сервере */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    post?: never;
    /** Удалить приглашение */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie: {
          /** @description Токен авторизации */
          zavodchat_token: parameters['zavodchat_token'];
        };
      };
      requestBody?: never;
      responses: {
        /** @description Приглашение успешно удалено */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description У пользователя нет прав на управление приглашениями */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Приглашения с таким ID не существует на сервере */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/servers/$server_id/bans/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Пагинированный список забаненных пользователей */
    get: {
      parameters: {
        query: {
          /** @description Начало диапазона (0 - последний бан, 1 - предпоследний бан, и т.д.) */
          start: number;
          /** @description Размер диапазона */
          count: number;
        };
        header?: never;
        path?: never;
        cookie: {
          /** @description Токен авторизации */
          zavodchat_token: parameters['zavodchat_token'];
        };
      };
      requestBody?: never;
      responses: {
        /** @description Список забаненных пользователей (может быть < count - означает конец массива банов) */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['User'][];
          };
        };
        /** @description Неправильный start (< 0, >= количеству банов) / слишком большой count */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    /** Забанить пользователя */
    post: {
      parameters: {
        query?: {
          /** @description Дата и время истечения бана (автоматически удаляется из базы данных через некоторый промежуток). Может быть "never" - бан навсегда */
          expires?: string;
          /** @description ID пользователя */
          ban_user_id?: number;
        };
        header?: never;
        path?: never;
        cookie: {
          /** @description Токен авторизации */
          zavodchat_token: parameters['zavodchat_token'];
        };
      };
      requestBody?: never;
      responses: {
        /** @description Пользователь успешно забанен */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Пользователь уже забанен */
        202: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Неправильная дата и время expires */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Нет прав на управление банами / попытка забанить >= роль */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    /** Разбанить пользователя */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie: {
          /** @description Токен авторизации */
          zavodchat_token: parameters['zavodchat_token'];
        };
      };
      requestBody?: never;
      responses: {
        /** @description Пользователь успешно разбанен */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Нет прав на управление банами */
        403: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Пользователь не забанен */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/servers/$server_id/roles': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Список ролей */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie: {
          /** @description Токен авторизации */
          zavodchat_token: parameters['zavodchat_token'];
        };
      };
      requestBody?: never;
      responses: {
        /** @description Список ролей в порядке от самой старшей до самой младшей */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Role'][];
          };
        };
      };
    };
    put?: never;
    /** Создать новую роль */
    post: {
      parameters: {
        query: {
          /** @description ID роли, перед (ниже) которой нужно вставить новую роль */
          next_role_id: number;
          /** @description Имя роли */
          name: string;
          /** @description Цвет роли в формате RGB */
          color: number;
          /** @description Набор разрешений 1. По умолчанию все разрешения 00 (унаследованы от младших ролей) */
          perms1?: number;
        };
        header?: never;
        path?: never;
        cookie: {
          /** @description Токен авторизации */
          zavodchat_token: parameters['zavodchat_token'];
        };
      };
      requestBody?: never;
      responses: {
        /** @description ID созданной роли */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            /** @example 17 */
            text: unknown;
          };
        };
        /** @description Неправильные параметры / попытка вставить роль перед default ролью */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/servers/$server_id/roles/$role_id': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Изменить параметры роли */
    put: {
      parameters: {
        query: {
          /** @description ID роли, перед (ниже) которой нужно вставить новую роль */
          next_role_id: number;
          /** @description Имя роли */
          name: string;
          /** @description Цвет роли в формате RGB */
          color: number;
          /** @description Набор разрешений 1. По умолчанию все разрешения 00 (унаследованы от младших ролей) */
          perms1?: number;
        };
        header?: never;
        path?: never;
        cookie: {
          /** @description Токен авторизации */
          zavodchat_token: parameters['zavodchat_token'];
        };
      };
      requestBody?: never;
      responses: {
        /** @description Роль успешно изменена */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Неправильные параметры / попытка вставить роль перед default ролью */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    post?: never;
    /** Удалить роль */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie: {
          /** @description Токен авторизации */
          zavodchat_token: parameters['zavodchat_token'];
        };
      };
      requestBody?: never;
      responses: {
        /** @description Роль успешно удалена */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/servers/$server_id/users/$user_id/roles/$role_id': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Назначить пользователю роль */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie: {
          /** @description Токен авторизации */
          zavodchat_token: parameters['zavodchat_token'];
        };
      };
      requestBody?: never;
      responses: {
        /** @description Роль успешно назначена */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Пользователь уже имеет эту роль */
        202: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    /** Отнять у пользователя роль */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie: {
          /** @description Токен авторизации */
          zavodchat_token: parameters['zavodchat_token'];
        };
      };
      requestBody?: never;
      responses: {
        /** @description Роль успешно отобрана */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Попытка отобрать роль по умолчанию */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/files/avatar/user/$filename': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Аватар пользователя */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Файл с аватаром */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            /** @example (Любой файл поддерживаемого формата изображений) */
            file: unknown;
          };
        };
        /** @description Файла не существует */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/files/avatar/server/$filename': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Аватар сервера */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Файл с аватаром */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            /** @example (Любой файл поддерживаемого формата изображений) */
            file: unknown;
          };
        };
        /** @description Файла не существует */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/files/upload/': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Загрузить файл на сервер */
    post: {
      parameters: {
        query: {
          /** @description Расширение файла */
          ext: string;
          /** @description Файл */
          file?: string;
        };
        header?: never;
        path?: never;
        cookie: {
          /** @description Токен авторизации */
          zavodchat_token: parameters['zavodchat_token'];
        };
      };
      requestBody?: never;
      responses: {
        /** @description Случайно сгенерированное имя файла */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            /** @example yN2ZIvEAa5YBT05qGVaBlG1mxDCY7n1v.png */
            text: unknown;
          };
        };
        /** @description Пустое расширение / слишком длинное расширение / пустой файл / файл не помещается на отведённое пользователю место на диске */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/files/upload/$filename': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Удалить свой файл с сервера */
    delete: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie: {
          /** @description Токен авторизации */
          zavodchat_token: parameters['zavodchat_token'];
        };
      };
      requestBody?: never;
      responses: {
        /** @description Файл был удалён */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
        /** @description Файла не существует */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/files/upload/$user_id/$filename': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Файл с сервера */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie: {
          /** @description Токен авторизации */
          zavodchat_token: parameters['zavodchat_token'];
        };
      };
      requestBody?: never;
      responses: {
        /** @description Файл */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            /** @example (Содержимое файла) */
            file: unknown;
          };
        };
        /** @description Файла не существует */
        404: {
          headers: {
            [name: string]: unknown;
          };
          content?: never;
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/params': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Конфигурация сервера */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Информация о конфигурации сервера */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Config'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    User: {
      /** @example 412 */
      id?: number;
      /** @example cyb3rc001 */
      name?: string;
      /** @example avatar_453912.png */
      avatar?: string;
      /** @example 0 */
      status?: number;
    };
    ServerUser: {
      /** @example 412 */
      id?: number;
      /** @example cyb3rc001 */
      name?: string;
      /** @example avatar_453912.png */
      avatar?: string;
      /** @example 0 */
      status?: number;
      /**
       * @description role_id ролей пользователя на сервере
       * @example [
       *       3,
       *       7
       *     ]
       */
      roles?: number[];
    };
    Server: {
      /** @example Зона */
      name?: string;
      /** @example avatar_453912.png */
      avatar?: string;
    };
    Channel: {
      /** @example 2 */
      id?: number;
      /** @example channel_test_vc */
      name?: string;
      /**
       * @description 0 - текстовый, 1 - голосовой
       * @example 1
       */
      type?: number;
      /**
       * @description user_id пользователей, которые подключены к голосовому каналу
       * @example [
       *       1,
       *       2
       *     ]
       */
      vc_users?: number[];
    };
    Message: {
      /** @example 17 */
      id?: number;
      /** @example 3 */
      author_id?: number;
      /**
       * Format: date
       * @example 2024-11-09 22:25:28.021376+03
       */
      sent?: string;
      /**
       * Format: date
       * @example 2024-11-09 22:25:28.021376+03
       */
      edited?: string;
      /** @example папа ты купил молоко? */
      text?: string;
    };
    Invite: {
      /** @example 1e1d184c-679a-494e-ba30-6f1f72bd221e */
      id?: string;
      /**
       * Format: date
       * @example 2024-11-13 00:00:00+03 или never
       */
      expires?: string;
      /** @example 3 */
      server_id?: number;
    };
    Role: {
      /** @example 2 */
      id?: number;
      /** @example 16711680 */
      color?: number;
      /** @example admin */
      name?: string;
      /** @example 158377 */
      perms1?: number;
    };
    Config: {
      /**
       * @description Максимальное количество каналов, которые можно создать на одном сервере
       * @example 50
       */
      max_channels_per_server?: number;
      /**
       * @description Максимальное количество записей, которые можно получить за один запрос пагинации
       * @example 50
       */
      max_get_count?: number;
      /**
       * @description Максимальное количество ролей, которые можно создать на одном сервере
       * @example 50
       */
      max_roles_per_server?: number;
      /**
       * @description Максимальный битрейт видео, который можно запросить при его включении в голосовом канале
       * @example 10240000
       */
      max_video_bitrate?: number;
      /**
       * @description Минимальная длина пароля при регистрации / изменении пароля
       * @example 8
       */
      min_password_length?: number;
      /**
       * @description Минимальная длина имени пользователя при регистрации / изменении пароля
       * @example 2
       */
      min_username_length?: number;
      /**
       * @description Максимальное количество серверов, которыми может владеть один пользователь
       * @example 10
       */
      servers_owned_per_user?: number;
      /**
       * @description Место на диске, выделенное под хранение файлов пользователей. Пропроционально разделено между всеми пользователями.
       * @example 10737418240
       */
      total_file_storage_size?: number;
      /**
       * @description Порт для сообщений WebSocket
       * @example 444
       */
      ws_port?: number;
      /**
       * @description Порт для сообщений WebSocket голосового канала
       * @example 445
       */
      ws_vc_port?: number;
    };
    /** @enum {integer} */
    UserStatus: 0 | 1 | 2 | 3;
    /** @enum {integer} */
    ChannelType: 0 | 1;
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
